networks:
  gitea:
    external: false

services:
  server:
    image: docker.gitea.com/gitea:1.24.2
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__admin__USER_DISABLED_FEATURES=deletion
      - GITEA__admin__USER_DISABLED_FEATURES=change_username
      - GITEA__admin__USER_DISABLED_FEATURES=change_full_name
      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__service__DEFAULT_ALLOW_CREATE_ORGANIZATION=false
      - GITEA__service__SHOW_REGISTRATION_BUTTON=false
      - GITEA__service__DEFAULT_USER_VISIBILITY=private
      - GITEA__service__ALLOWED_USER_VISIBILITY_MODES=private
      - GITEA__OAUTH2__ENABLED=true
      - GITEA__openid__ENABLE_OPENID_SIGNIN=false
      - GITEA__repository__DEFAULT_PRIVATE=true
      - GITEA__repository__FORCE_PRIVATE=true
    restart: unless-stopped
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data
