services:
  runner:
    image: docker.io/gitea/act_runner:latest
    environment:
      GITEA_INSTANCE_URL: "http://gitea.local"
      GITEA_RUNNER_REGISTRATION_TOKEN: "xxxxxx"
      GITEA_RUNNER_NAME: "runner-01"
      #GITEA_RUNNER_LABELS: "${RUNNER_LABELS}"
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock